# Site settings
title: Learning Git and Github
email: eric@smartlogic.io
description: > # this means to ignore newlines until "baseurl:"
  This workshop will help familiarize you with these tools for sharing and revising projects online.

baseurl: "/"
url: "http://bparker-vaughan.github.io"
twitter_username: Brittles_86
github_username:  bparker-vaughan

# Build settings
markdown: kramdown
